[Fix] Fix deletion of dashboard if it was trashed out of band (#4235)
## Changes

If a dashboard created by TF was trashed out of band, it could no longer
be deleted by TF.

Example TF configuration:
```hcl
terraform {
  required_providers {
    databricks = {
      source = "databricks/databricks"
      version = "1.58.0"
    }
  }
}

data "databricks_current_user" "me" {
  // This data source is used to get the current user's username
}

resource "databricks_dashboard" "this" {
  display_name = "Terraform test"
  parent_path = "/Workspace/Users/${data.databricks_current_user.me.user_name}/tf-dashboard-oob-deletion"
  warehouse_id = "58aa1b363649e722"
  serialized_dashboard = file("nyc_taxi_trip_analysis.lvdash.json")
}
```

If you apply this, and then run:
```
databricks lakeview trash <dashboard id>
```

The subsequent apply would error out with:
```
Error: cannot delete dashboard: dashboard [01efa39479a1128aae017018e434a747] lifecycle state [TRASHED] is not among the accepted states [Set(ACTIVE)]
```

It turns out trashing an already trashed dashboard returns an error.

This change guards against this condition returns success if the
underlying dashboard has already been trashed.

## Tests

- [x] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [ ] using Go SDK